name: Fetch X crypto feed

on:
  workflow_dispatch:
  schedule:
    - cron: '17,47 * * * *'

permissions:
  contents: write   # <-- lets the workflow push commits

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0              # full history so pull/rebase works
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: npm install              # <-- use install (you have no lockfile yet)
      - name: Run fetch
        run: node index.js
        env:
          X_BEARER_TOKEN: ${{ secrets.X_BEARER_TOKEN }}
      - name: Commit & push feed.json
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add feed.json
          git commit -m "chore: update feed.json [skip ci]" || exit 0
          git pull --rebase origin ${{ github.ref_name }} || true
          git push origin HEAD:${{ github.ref_name }}
