name: Fetch X crypto feed

on:
  workflow_dispatch:
  schedule:
    - cron: '17,47 * * * *'

# allow this workflow to push commits
permissions:
  contents: write

# prevent two overlapping runs from stomping each other
concurrency:
  group: feed-writer
  cancel-in-progress: false

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0            # full history so rebase works

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm ci

      - name: Run fetch
        run: node index.js
        env:
          X_BEARER_TOKEN: ${{ secrets.X_BEARER_TOKEN }}

      - name: Commit & push feed.json (rebase first)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add feed.json
          git commit -m "chore: update feed.json [skip ci]" || echo "No changes"
          # make sure we're up to date before pushing
          git fetch origin ${{ github.ref_name }}
          git pull --rebase origin ${{ github.ref_name }} || true
          git push origin HEAD:${{ github.ref_name }}
