name: Fetch X crypto feed

on:
  workflow_dispatch:
  schedule:
    - cron: '17,47 * * * *'   # twice an hour

permissions:
  contents: write             # allow pushing feed.json

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main           # now that your branch is 'main'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps    # use install (not ci) since no lockfile
        run: npm install

      - name: Run fetch
        run: node index.js
        env:
          X_BEARER_TOKEN: ${{ secrets.X_BEARER_TOKEN }}

      - name: Commit & push feed.json
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add feed.json
          git commit -m "chore: update feed.json [skip ci]" || echo "No changes"
          git push origin HEAD:main
