name: Fetch X crypto feed

on:
  workflow_dispatch:
  schedule:
    - cron: '17,47 * * * *'

permissions:
  contents: write     # allow GITHUB_TOKEN to push

concurrency:
  group: feed-json
  cancel-in-progress: true

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0          # full history so commits/pushes are smooth
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - name: Run fetch
        run: node index.js
        env:
          X_BEARER_TOKEN: ${{ secrets.X_BEARER_TOKEN }}

      # ⬇️ Let this action handle staging, committing and pushing feed.json
      - name: Commit & push feed.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update feed.json [skip ci]"
          branch: ${{ github.ref_name }}
          file_pattern: feed.json
