name: Fetch X crypto feed

on:
  workflow_dispatch:
  schedule:
    - cron: '17,47 * * * *'

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # No caching; no lock file needed
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install without requiring a lock file
      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Run fetch
        run: node index.js
        env:
          X_BEARER_TOKEN: ${{ secrets.X_BEARER_TOKEN }}

      - name: Commit & push feed.json
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add feed.json
          git commit -m "chore: update feed.json [skip ci]" || echo "No changes"
          git push
