name: Fetch X crypto feed

on:
  workflow_dispatch:
  schedule:
    # Run 2x/hour at :17 and :47 (UTC) to avoid top-of-hour congestion
    - cron: '17,47 * * * *'

# Allow this job to push feed.json back to the repo
permissions:
  contents: write

# Prevent overlapping runs from stepping on each other
concurrency:
  group: fetch-x-feed
  cancel-in-progress: false

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --no-audit --no-fund

      - name: Generate feed.json
        run: node index.js
        env:
          X_BEARER_TOKEN: ${{ secrets.X_BEARER_TOKEN }}

      - name: Commit & push feed.json
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add feed.json
          git commit -m "chore: update feed.json [skip ci]" || echo "No changes to commit"
          git push
